import { useState } from 'react';
import { ArrowLeft, CheckCircle2, Copy, Download, Share2, ShieldCheck, Check, Wallet } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

/* ── PDF receipt generator via canvas ── */
function generateReceiptCanvas(tx) {
  const canvas = document.createElement('canvas');
  canvas.width = 640;
  canvas.height = 900;
  const ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = '#050b1f';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Top gradient blob
  const grad = ctx.createRadialGradient(320, 200, 0, 320, 200, 400);
  grad.addColorStop(0, tx.type === 'credit' ? 'rgba(16,185,129,0.15)' : 'rgba(124,58,237,0.15)');
  grad.addColorStop(1, 'transparent');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Card background
  ctx.fillStyle = 'rgba(255,255,255,0.05)';
  roundRect(ctx, 40, 40, 560, 820, 32);
  ctx.fill();

  // Card border
  ctx.strokeStyle = 'rgba(255,255,255,0.1)';
  ctx.lineWidth = 1;
  roundRect(ctx, 40, 40, 560, 820, 32);
  ctx.stroke();

  // Logo / header
  ctx.fillStyle = '#fff';
  ctx.font = 'bold 28px -apple-system, BlinkMacSystemFont, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('MyWallet', 320, 110);

  ctx.fillStyle = 'rgba(255,255,255,0.4)';
  ctx.font = '14px -apple-system, sans-serif';
  ctx.fillText('Transaction Receipt', 320, 138);

  // Divider
  ctx.strokeStyle = 'rgba(255,255,255,0.08)';
  ctx.lineWidth = 1;
  ctx.beginPath(); ctx.moveTo(80, 158); ctx.lineTo(560, 158); ctx.stroke();

  // Status icon circle
  ctx.fillStyle = tx.type === 'credit' ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.1)';
  ctx.beginPath(); ctx.arc(320, 230, 44, 0, Math.PI * 2); ctx.fill();
  ctx.strokeStyle = tx.type === 'credit' ? 'rgba(16,185,129,0.4)' : 'rgba(255,255,255,0.2)';
  ctx.lineWidth = 1.5;
  ctx.beginPath(); ctx.arc(320, 230, 44, 0, Math.PI * 2); ctx.stroke();

  // Checkmark
  ctx.strokeStyle = tx.type === 'credit' ? '#10b981' : '#fff';
  ctx.lineWidth = 3;
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  ctx.beginPath();
  ctx.moveTo(302, 231); ctx.lineTo(316, 245); ctx.lineTo(340, 218);
  ctx.stroke();

  // Amount
  ctx.fillStyle = tx.type === 'credit' ? '#34d399' : '#fff';
  ctx.font = 'bold 52px -apple-system, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText(tx.amount.replace('+', '').replace('-', ''), 320, 330);

  // Status text
  ctx.fillStyle = 'rgba(255,255,255,0.5)';
  ctx.font = '13px -apple-system, sans-serif';
  ctx.fillText('✓  Completed Successfully', 320, 360);

  // Divider
  ctx.strokeStyle = 'rgba(255,255,255,0.08)';
  ctx.beginPath(); ctx.moveTo(80, 388); ctx.lineTo(560, 388); ctx.stroke();

  // Detail rows
  const rows = [
    ['Transaction ID', String(tx.id)],
    ['Date & Time',    tx.rawDate || tx.date],
    ['Category',      tx.category],
    [tx.type === 'credit' ? 'From' : 'To', tx.counterparty || '—'],
    ['Balance After',  tx.balanceAfter != null ? `₹${Number(tx.balanceAfter).toLocaleString('en-IN')}` : '—'],
  ];

  let y = 424;
  rows.forEach(([label, value]) => {
    ctx.textAlign = 'left';
    ctx.fillStyle = 'rgba(255,255,255,0.35)';
    ctx.font = '11px -apple-system, sans-serif';
    ctx.fillText(label.toUpperCase(), 80, y);

    ctx.textAlign = 'right';
    ctx.fillStyle = '#fff';
    ctx.font = '500 15px -apple-system, sans-serif';
    // Truncate long values
    const maxLen = 36;
    const displayVal = value.length > maxLen ? value.slice(0, maxLen) + '…' : value;
    ctx.fillText(displayVal, 560, y);

    ctx.strokeStyle = 'rgba(255,255,255,0.06)';
    ctx.beginPath(); ctx.moveTo(80, y + 14); ctx.lineTo(560, y + 14); ctx.stroke();
    y += 52;
  });

  // Total box
  ctx.fillStyle = 'rgba(255,255,255,0.05)';
  roundRect(ctx, 80, y + 10, 480, 72, 16);
  ctx.fill();
  ctx.textAlign = 'left';
  ctx.fillStyle = 'rgba(255,255,255,0.4)';
  ctx.font = 'bold 11px -apple-system, sans-serif';
  ctx.fillText('TOTAL AMOUNT', 110, y + 54);
  ctx.textAlign = 'right';
  ctx.fillStyle = '#fff';
  ctx.font = 'bold 22px -apple-system, sans-serif';
  ctx.fillText(tx.amount.replace('+', '').replace('-', ''), 530, y + 54);

  // Footer
  ctx.textAlign = 'center';
  ctx.fillStyle = 'rgba(255,255,255,0.2)';
  ctx.font = '12px -apple-system, sans-serif';
  ctx.fillText('Generated by MyWallet · payspace.vercel.app', 320, 840);

  return canvas;
}

function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.arcTo(x + w, y, x + w, y + r, r);
  ctx.lineTo(x + w, y + h - r);
  ctx.arcTo(x + w, y + h, x + w - r, y + h, r);
  ctx.lineTo(x + r, y + h);
  ctx.arcTo(x, y + h, x, y + h - r, r);
  ctx.lineTo(x, y + r);
  ctx.arcTo(x, y, x + r, y, r);
  ctx.closePath();
}

/* ── toast hook ── */
function useToast() {
  const [toast, setToast] = useState(null);
  const show = (msg, type = 'success') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 2500);
  };
  return [toast, show];
}

export default function TransactionDetail({ tx, onViewChange }) {
  const [copied, setCopied]     = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [sharing, setSharing]   = useState(false);
  const [toast, showToast]      = useToast();

  if (!tx) { onViewChange('dashboard'); return null; }
  const isCredit = tx.type === 'credit';

  /* ── Copy TX ID ── */
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(String(tx.id));
      setCopied(true);
      showToast('Transaction ID copied!');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      showToast('Copy failed', 'error');
    }
  };

  /* ── Download PDF ── */
  const handleDownload = () => {
    setDownloading(true);
    try {
      const canvas = generateReceiptCanvas(tx);
      const link = document.createElement('a');
      link.download = `payspace-receipt-${tx.id}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      showToast('Receipt downloaded!');
    } catch (e) {
      showToast('Download failed', 'error');
    } finally {
      setDownloading(false);
    }
  };

  /* ── Share Receipt ── */
  const handleShare = async () => {
    setSharing(true);
    const text = [
      `💳 MyWallet Transaction Receipt`,
      `─────────────────────`,
      `ID: ${tx.id}`,
      `Amount: ${tx.amount}`,
      `Category: ${tx.category}`,
      `Date: ${tx.rawDate || tx.date}`,
      tx.counterparty ? `${isCredit ? 'From' : 'To'}: ${tx.counterparty}` : '',
      tx.balanceAfter != null ? `Balance After: ₹${Number(tx.balanceAfter).toLocaleString('en-IN')}` : '',
      `─────────────────────`,
      `Powered by payspace.vercel.app`,
    ].filter(Boolean).join('\n');

    try {
      if (navigator.share) {
        // Try sharing image + text
        const canvas = generateReceiptCanvas(tx);
        canvas.toBlob(async (blob) => {
          const file = new File([blob], `receipt-${tx.id}.png`, { type: 'image/png' });
          try {
            await navigator.share({ title: 'Transaction Receipt', text, files: [file] });
            showToast('Shared successfully!');
          } catch {
            // Fallback to text-only share
            try { await navigator.share({ title: 'Transaction Receipt', text }); showToast('Shared!'); }
            catch { /* user cancelled */ }
          }
          setSharing(false);
        });
      } else {
        // Desktop fallback: copy to clipboard
        await navigator.clipboard.writeText(text);
        showToast('Receipt copied to clipboard!');
        setSharing(false);
      }
    } catch {
      showToast('Share failed', 'error');
      setSharing(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-8 flex flex-col justify-center pt-4 md:pt-12 pb-12">

      {/* Toast */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }}
            className={`fixed top-6 left-1/2 -translate-x-1/2 z-50 px-6 py-3 rounded-2xl text-sm font-bold shadow-2xl flex items-center gap-2 ${
              toast.type === 'error'
                ? 'bg-red-500/20 border border-red-500/40 text-red-300'
                : 'bg-green-500/20 border border-green-500/40 text-green-300'
            }`}
          >
            {toast.type !== 'error' && <Check size={16} />}
            {toast.msg}
          </motion.div>
        )}
      </AnimatePresence>

      <motion.button
        initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}
        onClick={() => onViewChange('history')}
        className="flex items-center gap-3 text-white/50 hover:text-white transition-colors w-fit text-lg font-bold bg-white/5 px-5 py-3 rounded-2xl border border-white/10"
      >
        <ArrowLeft className="w-5 h-5" /> Back to History
      </motion.button>

      <motion.div
        initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: 'easeOut' }}
        className="bg-white/5 backdrop-blur-3xl border border-white/10 p-8 md:p-14 rounded-[3rem] shadow-[0_30px_100px_rgba(0,0,0,0.5)] relative overflow-hidden"
      >
        <div className={`absolute top-[-30%] left-[-20%] w-[80%] h-[80%] blur-[120px] rounded-full pointer-events-none ${isCredit ? 'bg-green-500/20' : 'bg-orange-500/20'}`} />

        {/* Header */}
        <div className="text-center border-b border-white/10 pb-12 mb-10 relative z-10">
          <motion.div
            initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ delay: 0.2, type: 'spring' }}
            className={`w-24 h-24 rounded-[2rem] flex items-center justify-center mx-auto mb-8 shadow-inner border ${isCredit ? 'bg-green-500/20 text-green-400 border-green-500/30' : 'bg-white/10 text-white/80 border-white/20'}`}
          >
            <CheckCircle2 className="w-12 h-12" />
          </motion.div>
          <motion.h2
            initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
            className={`font-syne text-5xl md:text-6xl font-black tracking-tighter mb-4 ${isCredit ? 'text-green-400' : 'text-white'}`}
          >
            {tx.amount}
          </motion.h2>
          <motion.p
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
            className="text-white/50 font-bold text-sm uppercase tracking-widest flex items-center justify-center gap-2"
          >
            <ShieldCheck size={16} className="text-green-400" /> Completed Successfully
          </motion.p>
        </div>

        {/* Details */}
        <motion.div
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}
          className="space-y-6 relative z-10"
        >
          <DetailRow label="Transaction ID" value={tx.id} copyable onCopy={handleCopy} copied={copied} />
          <DetailRow label="Date & Time"    value={tx.rawDate || tx.date} />
          <DetailRow label="Category"       value={<span className="bg-white/10 px-3 py-1 rounded-lg text-white/90">{tx.category}</span>} />

          <div className="h-px w-full bg-white/10 my-8" />

          <DetailRow label={isCredit ? 'From' : 'To'}          value={tx.counterparty || '—'} highlight />
          {tx.balanceAfter != null && (
            <DetailRow label="Balance After" value={`₹${Number(tx.balanceAfter).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`} />
          )}

          <div className="h-px w-full bg-white/10 my-8" />

          <div className="flex justify-between items-center bg-white/5 p-6 rounded-3xl border border-white/10">
            <span className="text-white/50 font-bold text-sm uppercase tracking-widest">Total Amount</span>
            <span className="font-syne font-black text-3xl tracking-tighter text-white">
              {tx.amount.replace('+', '').replace('-', '')}
            </span>
          </div>
        </motion.div>

        {/* Action Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.6 }}
          className="flex flex-col sm:flex-row gap-4 mt-12 relative z-10"
        >
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="flex-1 bg-white/10 border border-white/20 py-5 px-6 rounded-2xl flex items-center justify-center gap-3 hover:bg-white/20 active:scale-95 transition-all font-bold text-lg text-white disabled:opacity-50"
          >
            <Download className={`w-5 h-5 ${downloading ? 'animate-bounce' : ''}`} />
            {downloading ? 'Generating…' : 'Download Receipt'}
          </button>
          <button
            onClick={handleShare}
            disabled={sharing}
            className="flex-1 bg-white border border-transparent text-black py-5 px-6 rounded-2xl flex items-center justify-center gap-3 hover:bg-white/90 active:scale-95 transition-all font-bold text-lg shadow-[0_0_30px_rgba(255,255,255,0.2)] disabled:opacity-50"
          >
            <Share2 className={`w-5 h-5 ${sharing ? 'animate-pulse' : ''}`} />
            {sharing ? 'Sharing…' : 'Share Receipt'}
          </button>
        </motion.div>
      </motion.div>
    </div>
  );
}

function DetailRow({ label, value, highlight, copyable, onCopy, copied }) {
  return (
    <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-2 sm:gap-0 p-2">
      <span className="text-white/40 font-bold text-xs uppercase tracking-widest">{label}</span>
      <div className="flex items-center gap-3">
        <span className={`font-medium text-lg text-right ${highlight ? 'text-white font-bold' : 'text-white/80'}`}>{value}</span>
        {copyable && (
          <button onClick={onCopy} className="text-white/30 hover:text-white transition-colors" title="Copy">
            {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
          </button>
        )}
      </div>
    </div>
  );
}